server:
  name: erp-finance-service
  http_port: 8091

database:
  driver: postgres
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: oa_finance
  sslmode: disable

kafka:
  brokers:
    - localhost:9092
